version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
      size: "medium"

    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Install nuget dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          command: msbuild restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run: 
          name: build
          command: msbuild CapaPresentaciones\CapaPresentaciones.csproj /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64|ARM"
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage

workflows:
  version: 2
  build_and_upload_artifact:
    jobs:
      - build