version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\Proyecto Final\AppSistemaTutoria
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Install nuget dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          command: msbuild restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\Proyecto Final\AppSistemaTutoria\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Build step"
          command: msbuild CapaPresentaciones\CapaPresentaciones.csproj /p:Configuration=Release /p:AppxBundle=Always /p:AppxBundlePlatforms="x86|x64|ARM"
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\AppSistemaTutoria.exe

workflows:
  PruebasFormulario:
    jobs:
      - build