version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  build:
    executor:
      name: win/default
    working_directory: C:\Users\circleci\project\Proyecto Final\AppSistemaTutoria
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Install nuget dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\project\Proyecto Final\AppSistemaTutoria\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Build step"
          command: dotnet publish -c Release -r win10-x64
      - store_artifacts:
          path: .\bin\Release\netcoreapp2.1\win10-x64\publish\AppSistemaTutoria.exe

workflows:
  PruebasFormulario:
    jobs:
      - build