version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    description: Setup and run application tests
    executor:
      name: windows/default
      size: medium
    working_directory: C:\Users\circleci\project\Proyecto Final\AppSistemaTutoria
    steps:
      - checkout:
          path: C:\Users\circleci\project
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Install nuget dependencies"
          command: nuget restore
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - save_cache:
          paths:
            - C:\Users\circleci\Proyecto Final\AppSistemaTutoria\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "CapaPresentaciones\CapaPresentaciones.csproj" }}
      - run:
          name: "Run Application Tests"
          command: msbuild test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - run:
          name: "Print Working Directory"
          command: pwd
      - store_artifacts:
          path: C:\Users\circleci\project\test_coverage
workflows:
  test_and_build:
    jobs:
      - test